# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1249, 905)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(380, 650, 821, 211))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.playerCardLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.playerCardLayout.setContentsMargins(0, 0, 0, 0)
        self.playerCardLayout.setObjectName("playerCardLayout")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(180, 0, 821, 221))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.enemyCardLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.enemyCardLayout.setContentsMargins(0, 0, 0, 0)
        self.enemyCardLayout.setObjectName("enemyCardLayout")
        self.currentCard = QtWidgets.QLabel(parent=self.centralwidget)
        self.currentCard.setGeometry(QtCore.QRect(560, 410, 47, 13))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.currentCard.sizePolicy().hasHeightForWidth())
        self.currentCard.setSizePolicy(sizePolicy)
        self.currentCard.setText("")
        self.currentCard.setObjectName("currentCard")
        self.deck = QtWidgets.QLabel(parent=self.centralwidget)
        self.deck.setGeometry(QtCore.QRect(1090, 410, 47, 13))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deck.sizePolicy().hasHeightForWidth())
        self.deck.setSizePolicy(sizePolicy)
        self.deck.setText("")
        self.deck.setObjectName("deck")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1249, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
